[project]
name = "slcm"
description = "Student Life Cycle Management"
requires-python = ">=3.10,<3.15"
readme = "README.md"
dynamic = ["version"]

authors = [
    { name = "Nishanth", email = "nishanth.a@azimpremjifoundation.org" },
    { name = "TFSS", email = "tech4socialsector@azimpremjifoundation.org" }
]

dependencies = [
    "qrcode[pil]>=7.4.2",
    "Pillow>=10.2.0",
    "pypdf>=3.0.0"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=15,<18"
qrcode = "~=7.4.2"
Pillow = "~=10.2.0"
pypdf = ">=3.0.0"
