-- Precalculating Summary First
WITH 
-- 1. Office Hours Held (Denominator for Office Hours)
OfficeHoursHeld AS (
    SELECT 
        course_offering,
        COALESCE(SUM(duration_hours), 0) as total_oh_held
    FROM `tabAttendance Session`
    WHERE session_type = 'Office Hour' 
    AND session_status = 'Conducted'
    AND docstatus < 2
    GROUP BY course_offering
),

-- 2. Regular Classes Held (Denominator for Classes)
RegularClassesHeld AS (
    SELECT 
        course_offering,
        COALESCE(SUM(duration_hours), 0) as total_classes_held
    FROM `tabAttendance Session`
    WHERE session_type IN ('Lecture', 'Tutorial') 
    AND session_status = 'Conducted'
    AND docstatus < 2
    GROUP BY course_offering
),

-- 3. Student Attributes (Attended Hours breakdown)
StudentAttendanceStats AS (
    SELECT 
        student,
        course_offer as course_offering,
        -- Regular Attendance (Lecture/Tutorial)
        COALESCE(SUM(CASE 
            WHEN session_type IN ('Lecture', 'Tutorial') AND status IN ('Present', 'Late', 'Excused') 
            THEN hours_counted ELSE 0 END), 0) as attended_regular_hours,
        -- Office Hours Attended
        COALESCE(SUM(CASE 
            WHEN session_type = 'Office Hour' AND status IN ('Present', 'Late', 'Excused') 
            THEN hours_counted ELSE 0 END), 0) as attended_oh_hours
    FROM `tabStudent Attendance`
    WHERE docstatus < 2
    GROUP BY student, course_offer
),

-- 4. Condonation Data (Aggregated per student-course)
CondonationData AS (
    SELECT 
        student,
        course_offering,
        -- Check if ANY application is applied
        CASE WHEN COUNT(*) > 0 THEN 'Yes' ELSE 'No' END as applied_condonation,
        -- Check Status (If one is Approved, overall is Approved, else Pending/Mixed)
        CASE 
            WHEN SUM(CASE WHEN final_status = 'Approved' THEN 1 ELSE 0 END) > 0 THEN 'Approved'
            WHEN SUM(CASE WHEN final_status = 'Rejected' THEN 1 ELSE 0 END) = COUNT(*) THEN 'Rejected'
            ELSE 'Applied / Pending' 
        END as condonation_status,
        -- Approved Hours ONLY
        COALESCE(SUM(CASE WHEN final_status = 'Approved' THEN number_of_hours ELSE 0 END), 0) as approved_condonation_hours,
        -- Concatenated Remarks & Attachments
        GROUP_CONCAT(DISTINCT condonation_reason SEPARATOR '; ') as condonation_reason,
        GROUP_CONCAT(DISTINCT remarks SEPARATOR '; ') as condonation_remarks,
        GROUP_CONCAT(DISTINCT proof_document SEPARATOR ', ') as condonation_attachments
    FROM `tabStudent Attendance Condonation`
    WHERE docstatus < 2
    GROUP BY student, course_offering
),

-- 5. FA / MFA Data (Aggregated per student-course)
FAMFAData AS (
    SELECT 
        student,
        course, -- Links to Course (Core), not Offering
        CASE WHEN COUNT(*) > 0 THEN 'Yes' ELSE 'No' END as applied_famfa,
        CASE 
            WHEN SUM(CASE WHEN status = 'Approved' THEN 1 ELSE 0 END) > 0 THEN 'Approved'
            WHEN SUM(CASE WHEN status = 'Rejected' THEN 1 ELSE 0 END) = COUNT(*) THEN 'Rejected'
            ELSE 'Pending' 
        END as famfa_status,
        -- Hours: Currently Schema does NOT have hours. Defaults to 0. 
        -- If exemption logic exists, it should be added here.
        0 as approved_famfa_hours, 
        GROUP_CONCAT(DISTINCT reason SEPARATOR '; ') as famfa_reason,
        GROUP_CONCAT(DISTINCT description SEPARATOR '; ') as famfa_remarks,
        GROUP_CONCAT(DISTINCT proof_document SEPARATOR ', ') as famfa_attachments
    FROM `tabFA MFA Application`
    WHERE docstatus < 2
    GROUP BY student, course
)

SELECT 
    -- 1. S.No (Row Number generated by Report View usually, but logically here)
    ROW_NUMBER() OVER (ORDER BY stu.name ASC) as `S.No`,
    
    -- 2. Student ID
    stu.name as `Student ID`,
    
    -- 3. Student Name
    stu.first_name as `Student Name`,
    
    -- 4. Section
    COALESCE(summary.section, '') as `Section`,
    
    -- 5. Course Name
    COALESCE(co.course_title, summary.course) as `Course Name`,
    
    -- --- CONDONATION DETAILS ---
    -- 6. Applied for Condonation
    COALESCE(cond.applied_condonation, 'No') as `Applied for Condonation`,
    
    -- 7. Condonation Attachment
    cond.condonation_attachments as `Condonation Attachment`,
    
    -- 8. Condonation Status
    COALESCE(cond.condonation_status, 'Not Applied') as `Condonation Status`,
    
    -- 9. Condonation Remarks
    cond.condonation_reason as `Condonation Reason`,
    cond.condonation_remarks as `Condonation Remarks`,
    
    -- 10. Number of Hours for Condonation
    COALESCE(cond.approved_condonation_hours, 0) as `Condonation Hours`,
    
    -- --- FA / MFA DETAILS ---
    -- 11. Applied for FA / MFA
    COALESCE(fa.applied_famfa, 'No') as `Applied for FA / MFA`,
    
    -- 12. FA / MFA Attachment
    fa.famfa_attachments as `FA / MFA Attachment`,
    
    -- 13. FA / MFA Status
    COALESCE(fa.famfa_status, 'Not Applied') as `FA / MFA Status`,
    
    -- 14. FA / MFA Remarks
    fa.famfa_reason as `FA / MFA Reason`,
    fa.famfa_remarks as `FA / MFA Remarks`,
    
    -- 15. Number of Hours for FA / MFA
    COALESCE(fa.approved_famfa_hours, 0) as `FA / MFA Hours`,
    
    -- --- ATTENDANCE METRICS ---
    -- 16. Total Classes Held
    COALESCE(rch.total_classes_held, 0) as `Total Classes Held`,
    
    -- 17. Total Office Hours Held
    COALESCE(ohh.total_oh_held, 0) as `Total Office Hours Held`,
    
    -- 18. Total Hours (Classes + Office Hours)
    (COALESCE(rch.total_classes_held, 0) + COALESCE(ohh.total_oh_held, 0)) as `Total Hours`,
    
    -- 19. Attendance Percentage BEFORE applying Condonation / FA / MFA
    -- Formula: (Attended Regular + Attended Office) / (Total Classes + Total Office)
    CASE 
        WHEN (COALESCE(rch.total_classes_held, 0) + COALESCE(ohh.total_oh_held, 0)) > 0 
        THEN ROUND(
            ((COALESCE(sas.attended_regular_hours, 0) + COALESCE(sas.attended_oh_hours, 0)) / 
            (COALESCE(rch.total_classes_held, 0) + COALESCE(ohh.total_oh_held, 0))) * 100
        , 2)
        ELSE 0 
    END as `Attendance Percentage Before`,
    
    -- 20. Number of Hours Absent
    -- Formula: Total Hours - (Attended Regular + Attended Office)
    ((COALESCE(rch.total_classes_held, 0) + COALESCE(ohh.total_oh_held, 0)) - 
     (COALESCE(sas.attended_regular_hours, 0) + COALESCE(sas.attended_oh_hours, 0))) as `Hours Absent`,
     
    -- 21. Total Hours AFTER considering Condonation, FA, MFA
    -- Interpreted as: Final Effective Attended Hours
    -- Formula: (Attended Regular + Attended Office) + Approved Condonation + Approved FA/MFA
    (COALESCE(sas.attended_regular_hours, 0) + COALESCE(sas.attended_oh_hours, 0) + 
     COALESCE(cond.approved_condonation_hours, 0) + COALESCE(fa.approved_famfa_hours, 0)) as `Final Attended Hours`,

    -- 22. Attendance Percentage AFTER
    CASE 
        WHEN (COALESCE(rch.total_classes_held, 0) + COALESCE(ohh.total_oh_held, 0)) > 0 
        THEN ROUND(
            ((COALESCE(sas.attended_regular_hours, 0) + COALESCE(sas.attended_oh_hours, 0) + 
              COALESCE(cond.approved_condonation_hours, 0) + COALESCE(fa.approved_famfa_hours, 0)) / 
            (COALESCE(rch.total_classes_held, 0) + COALESCE(ohh.total_oh_held, 0))) * 100
        , 2)
        ELSE 0 
    END as `Attendance Percentage After`
     
     -- Optional: Final Percentage (Not explicitly requested as a column but implied by requirements)
     -- , CASE WHEN (Total Hours) > 0 THEN ...

FROM `tabAttendance Summary` summary
JOIN `tabStudent Master` stu ON summary.student = stu.name
LEFT JOIN `tabCourse Offering` co ON summary.course_offering = co.name
LEFT JOIN RegularClassesHeld rch ON summary.course_offering = rch.course_offering
LEFT JOIN OfficeHoursHeld ohh ON summary.course_offering = ohh.course_offering
LEFT JOIN StudentAttendanceStats sas ON summary.student = sas.student AND summary.course_offering = sas.course_offering
LEFT JOIN CondonationData cond ON summary.student = cond.student AND summary.course_offering = cond.course_offering
LEFT JOIN FAMFAData fa ON summary.student = fa.student AND summary.course = fa.course

WHERE 
    summary.docstatus < 2
    AND (%(department)s IS NULL OR stu.department = %(department)s)
    AND (%(program)s IS NULL OR stu.programme = %(program)s)
    AND (%(batch)s IS NULL OR stu.batch_year = %(batch)s)
    AND (%(section)s IS NULL OR summary.section = %(section)s)
    AND (%(course)s IS NULL OR COALESCE(co.course_title, summary.course) = %(course)s)

ORDER BY stu.name ASC, co.course_title ASC
